-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Organization"
(
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    country character varying(100) NOT NULL,
    reg_date date NOT NULL,
    PRIMARY KEY (name),
    CONSTRAINT email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.volunteer
(
    id serial NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    birth_date date,
    organization character varying(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.event
(
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    location character varying(2048),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.org_event
(
    org_name character varying(255) NOT NULL,
    event_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.voluntering_for
(
    org_vol_id serial NOT NULL,
    volunteer_id serial NOT NULL,
    org_name character varying(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    PRIMARY KEY (org_vol_id)
);

CREATE TABLE IF NOT EXISTS public.event_volunteer
(
    volunteer_id integer NOT NULL,
    event_id integer NOT NULL,
    PRIMARY KEY (volunteer_id, event_id)
);

ALTER TABLE IF EXISTS public.volunteer
    ADD FOREIGN KEY (organization)
    REFERENCES public."Organization" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.org_event
    ADD FOREIGN KEY (org_name)
    REFERENCES public."Organization" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.org_event
    ADD FOREIGN KEY (event_id)
    REFERENCES public.event (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.voluntering_for
    ADD FOREIGN KEY (org_name)
    REFERENCES public."Organization" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.voluntering_for
    ADD FOREIGN KEY (volunteer_id)
    REFERENCES public.volunteer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.event_volunteer
    ADD FOREIGN KEY (volunteer_id)
    REFERENCES public.volunteer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.event_volunteer
    ADD FOREIGN KEY (event_id)
    REFERENCES public.event (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;